# Generated by Django 5.0.4 on 2024-06-04 12:05

import trello.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otprequest_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=trello.apps.users.models.generate_otp, max_length=4),
        ),
    ]
